/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xuetang9_xm_javabase_utils_StringDataUtilsUp */

#ifndef _Included_com_xuetang9_xm_javabase_utils_StringDataUtilsUp
#define _Included_com_xuetang9_xm_javabase_utils_StringDataUtilsUp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xuetang9_xm_javabase_utils_StringDataUtilsUp
 * Method:    setInstance
 * Signature: (Lcom/xuetang9/xm/javabase/utils/StringDataUtilsUp;)V
 */
JNIEXPORT void JNICALL Java_com_xuetang9_xm_javabase_utils_StringDataUtilsUp_setInstance
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
